/**
 * EffectType — Visual effect type IDs.
 * Mirrors C++ EffectType enum from Sources/Client/EffectType.h.
 */

export enum EffectType {
	INVALID = 0,
	NORMAL_HIT = 1,
	ARROW_FLYING = 2,
	GOLD_DROP = 4,
	FIREBALL_EXPLOSION = 5,
	ENERGY_BOLT_EXPLOSION = 6,
	MAGIC_MISSILE_EXPLOSION = 7,
	BURST_SMALL = 8,
	BURST_MEDIUM = 9,
	LIGHTNING_ARROW_EXPLOSION = 10,
	BURST_SMALL_GRENADE = 11,
	BURST_LARGE = 12,
	BUBBLES_DRUNK = 13,
	FOOTPRINT = 14,
	RED_CLOUD_PARTICLES = 15,
	PROJECTILE_GENERIC = 16,
	ICE_STORM = 17,
	IMPACT_BURST = 18,
	CRITICAL_STRIKE_1 = 20,
	CRITICAL_STRIKE_2 = 21,
	CRITICAL_STRIKE_3 = 22,
	CRITICAL_STRIKE_4 = 23,
	CRITICAL_STRIKE_5 = 24,
	CRITICAL_STRIKE_6 = 25,
	CRITICAL_STRIKE_7 = 26,
	CRITICAL_STRIKE_8 = 27,
	MASS_FIRE_STRIKE_CALLER1 = 30,
	MASS_FIRE_STRIKE_CALLER3 = 31,
	FOOTPRINT_RAIN = 32,
	FIRE_AURA_GROUND = 61,
	MS_CRUSADE_CASTING = 100,
}
